var UplinkData =
    [
        {id:'1',value:'社区社区社区社区1',
            childs:[
                {
                    id:'2',
                    value:'小区2',
                    childs:[
                        {
                            id:'1',
                            value:'1号楼',
                            childs:[
                                {
                                    id:'1',
                                    value:'1单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'2',
                                    value:'2单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'3',
                                    value:'3单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            id:'2',
                            value:'2号楼',
                            childs:[
                                {
                                    id:'1',
                                    value:'1单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'2',
                                    value:'2单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'3',
                                    value:'3单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            id:'3',
                            value:'3号楼',
                            childs:[
                                {
                                    id:'1',
                                    value:'1单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'2',
                                    value:'2单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'3',
                                    value:'3单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            id:'4',
                            value:'4号楼',
                            childs:[
                                {
                                    id:'1',
                                    value:'1单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'2',
                                    value:'2单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'3',
                                    value:'3单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            id:'5',
                            value:'5号楼',
                            childs:[
                                {
                                    id:'1',
                                    value:'1单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'2',
                                    value:'2单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'3',
                                    value:'3单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
            ]
        },
        {
            id:'2',
            value:'社区2',
            childs:[
                {
                    id:'1',
                    value:'小区1'
                },
                {
                    id:'2',
                    value:'小区2',
                    childs:[
                        {
                            id:'1',
                            value:'1号楼',
                            childs:[
                                {
                                    id:'1',
                                    value:'1单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'2',
                                    value:'2单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'3',
                                    value:'3单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            id:'2',
                            value:'2号楼',
                            childs:[
                                {
                                    id:'1',
                                    value:'1单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'2',
                                    value:'2单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'3',
                                    value:'3单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            id:'3',
                            value:'3号楼',
                            childs:[
                                {
                                    id:'1',
                                    value:'1单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'2',
                                    value:'2单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'3',
                                    value:'3单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            id:'4',
                            value:'4号楼',
                            childs:[
                                {
                                    id:'1',
                                    value:'1单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'2',
                                    value:'2单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'3',
                                    value:'3单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            id:'5',
                            value:'5号楼',
                            childs:[
                                {
                                    id:'1',
                                    value:'1单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'2',
                                    value:'2单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                },
                                {
                                    id:'3',
                                    value:'3单元',
                                    childs:[
                                        {
                                            id:'1',
                                            value:'101'
                                        },
                                        {
                                            id:'2',
                                            value:'102'
                                        },
                                        {
                                            id:'3',
                                            value:'201'
                                        },
                                        {
                                            id:'4',
                                            value:'202'
                                        },
                                        {
                                            id:'5',
                                            value:'301'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    id:'3',
                    value:'小区3'
                },
                {
                    id:'4',
                    value:'小区4'
                }
            ]
        },
        {
            id:'3',
            value:'社区3',
            childs:[
                {
                    id:'1',
                    value:'小区1'
                },
                {
                    id:'2',
                    value:'小区2'
                }
            ]
        },
        {
            id:'4',
            value:'社区4',
            childs:[
                {
                    id:'1',
                    value:'小区1'
                },
                {
                    id:'2',
                    value:'小区2'
                },
                {
                    id:'3',
                    value:'小区2'
                }
            ]
        },
        {
            id:'5',
            value:'社区5',
            childs:[
                {
                    id:'1',
                    value:'小区1'
                },
                {
                    id:'2',
                    value:'小区2'
                },
                {
                    id:'3',
                    value:'小区3'
                }
            ]
        }
    ];
var UplinkData0 = [
    {
        id:'1',
        value:'社区',
        childs:[
            {
                id:'1',
                value:'小区',
                childs:[
                    {
                        id:'1',
                        value:'内铺',
                        childs:[
                            {
                                id:'1',
                                value:'1号'
                            },
                            {
                                id:'2',
                                value:'2号'
                            },
                            {
                                id:'3',
                                value:'3号'
                            },
                            {
                                id:'4',
                                value:'4号'
                            }
                        ]
                    },
                    {
                        id:'2',
                        value:'外铺',
                        childs:[
                            {
                                id:'1',
                                value:'1号'
                            },
                            {
                                id:'2',
                                value:'2号'
                            },
                            {
                                id:'3',
                                value:'3号'
                            },
                            {
                                id:'4',
                                value:'4号'
                            }
                        ]
                    }
                ]
            },
            {
                id:'2',
                value:'街',
                childs:[
                    {
                        id:'1',
                        value:'1号'
                    },
                    {
                        id:'2',
                        value:'2号'
                    },
                    {
                        id:'3',
                        value:'3号'
                    },
                    {
                        id:'4',
                        value:'4号'
                    }
                ]
            },
            {
                id:'3',
                value:'路',
                childs:[
                    {
                        id:'1',
                        value:'1号'
                    },
                    {
                        id:'2',
                        value:'2号'
                    },
                    {
                        id:'3',
                        value:'3号'
                    },
                    {
                        id:'4',
                        value:'4号'
                    }
                ]
            }
        ]
    }
]